jobs:
  include:
    - name: Report
      if: type = cron

      language: python

      python:
        - '3.5'

      install:
        - pipenv install

      script:
        - .travis/report.sh

branches:
  only:
    - master
    - /^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)([\.\-].*)?$/
