jobs:
  include:
    - name: Report
      if: type = cron

      language: python

      python:
        - '3.5'

      install:
        - pipenv install

      script:
        - .travis/report.sh

    - name: Build web
      if: type != cron

      language: node_js
      node_js:
        - '10'

      env:
        global:
          - NODE_OPTIONS='--max_old_space_size=4096'

      script:
        - .travis/build-web.sh

branches:
  only:
    - master
    - /^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)([\.\-].*)?$/
