name: Build

on:
  push:
    branches:
      - master
  pull_request: {}

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_CONFIG_COLOR: always

jobs:
  web:
    name: Build
    runs-on: ubuntu-20.04
    environment: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Build
        run: .github/scripts/build-web.sh
